### ISSUE TITLE
Add option Internet Gateway and DNS IP

### ISSUE THREAD

**Issue by Anime4000** [freelan-developers/freelan-all#15]
I has been looking better P2P VPN,
so far I tried Hamachi, LAN Bridger, Tunngle, TeamViewer VPN and SoftEther.
These VPN quite unstable in some computer and SoftEther cause game frequent disconnect and not Direct client to client, LAN Bridger seem no longer support and not decentralized.

FreeLAN give much more faster, decentralized, lightweight and less overhead, so far none I found.

I has been tweaking FreeLAN, once session connected, I start share my internet to FreeLAN adapter, and other PC configure an manual IP Address, and have internet access!

problem is when FreeLAN exit, and re-open, it IP revert to auto.
I disable DHCP proxy, manual IP changed to follow FreeLAN configuration.

I would like to see Internet Gateway and DNS on FreeLAN configuration. So I can install on my server and other client get an Internet access while in P2P mode, just like Virtual Home!

It's because my ISP blocking port 6667 TCP cause Red Alert 3 and Crysis 2 unable to login EA network or play online, I used SoftEther and game match cannot start due Error "Kick player that have connectivity issue", FreeLAN was not... :)

**Comment by ereOn** [comment]
Interesting (although a bit old) entry for implementing this on Windows [here](http://www.codeproject.com/Articles/7654/Programmatically-Changing-IP-address-Domain-Name-S).

**Comment by ereOn** [comment]
For the record, this has finally been implemented :)

Under Windows, system calls make this easy to automate.

Under Mac OS X and Linux, the user is responsible for providing a script that will add/remove DNS server entries. With the upcoming release, that's the best I can do.

**Comment by Anime4000** [comment]
:+1: epic implementation!

**Comment by ereOn** [comment]
Note that the actual implementation is not just the mentionned commit but the 15 or so commits before as well.

**Comment by Anime4000** [comment]
by the way, in Windows, when FreeLAN connected, all traffic redirected to FreeLAN network?
and this settings, it will be P2P with Gateway (Server) right?

**Comment by ereOn** [comment]
@Anime4000 Depends on the route you setup :)

You can indeed redirect all trafic, or just some. And you can configure this on a remote peer that will transmit its routes automatically. You have all the options in the world !

**Comment by Anime4000** [comment]
@ereOn Man... it's make virtual home or home over internet :+1:
