### ISSUE TITLE
Embed tuntaposx in the installer

### ISSUE THREAD

**Issue by ereOn** [freelan-developers/freelan-all#30]
We currently rely on tuntaposx to be installed for freelan to work.

This assumption is painful for the user: Viscosity and Tunnelblick both embed their own tuntaposx packaged extensions (with custom version string so they do not collide with the legacy one).

Viscosity also seems to dynamically load the extension whenever needed and unloads it if it was him that loaded it in the first place. That would be a nice behavior to have in freelan. (See [#6](https://github.com/freelan-developers/freelan/issues/6))

**Comment by stephank** [comment]
There's apparently also utun starting in 10.7, which is already the minimum for freelan. Maybe this can replace tuntaposx completely?

http://www.opensource.apple.com/source/xnu/xnu-2782.1.97/bsd/net/if_utun.h

**Comment by ereOn** [comment]
@stephank : That is interesting indeed, but it would seem it doesn't support tap adapters sadly.

I will still look at it at it could be a nice alternative for tun-only configurations.

**Comment by ereOn** [comment]
It seems tuntaposx was updated (in regards to signing need for Yosemite), and should be updated in the repository.
