### ISSUE TITLE
Using path with space

### ISSUE THREAD

**Issue by S-Erion** [freelan-developers/freelan-all#39]
Hi all,

Using Microsoft Windows 7 x64, I tried to set the security path to the installation path and I have an issue.
After some tests, it appears that FreeLAN doesn't realy like the keys signature_certificate_file, signature_private_key_file, authority_certificate_file if there contains some spaces.

Configuration : 
	OS : Microsoft Windows 7 Enterprise / Professional SP1 x64bits
	Installation Path : C:\Program Files\FreeLAN\
	Binary Path : C:\Program Files\FreeLAN\bin
	Config File : C:\Program Files\FreeLAN\config\freelan.cfg

Tests & results :
1-
	signature_certificate_file=C:\ProgramData\FreeLAN\laptop-nxo.crt
	signature_private_key_file=C:\Program Files\FreeLAN\config\laptop-nxo.key
	authority_certificate_file=C:\ProgramData\FreeLAN\ca.crt
- CLI : KO 
	c:\Program Files\FreeLAN\bin>freelan.exe -c ..\config\freelan.cfg
	Reading configuration file at: "c:\Program Files\FreeLAN\bin\..\config\freelan.cfg"
	Error: the argument ('C:\Program Files\FreeLAN\config\laptop-nxo.key') for option  'security.signature_private_key_file' is invalid
- Windows Service : KO

2-
	signature_certificate_file=C:\ProgramData\FreeLAN\laptop-nxo.crt
	signature_private_key_file="C:\Program Files\FreeLAN\config\laptop-nxo.key"
	authority_certificate_file="C:\Program Files\FreeLAN\config\ca.crt"
- CLI : KO 
	c:\Program Files\FreeLAN\bin>freelan.exe -c ..\config\freelan.cfg
	Reading configuration file at: "c:\Program Files\FreeLAN\bin\..\config\freelan.cfg"
	Error: No such file: "C:\Program Files\FreeLAN\bin\Program Files\FreeLAN\config\ca.crt"
- Windows Service : KO

3-
	signature_certificate_file=C:\ProgramData\FreeLAN\laptop-nxo.crt
	signature_private_key_file=C:\ProgramData\FreeLAN\laptop-nxo.key
	authority_certificate_file=..\config\ca.crt
- CLI : OK	
- Windows Service : KO

4-
	signature_certificate_file=C:\ProgramData\FreeLAN\laptop-nxo.crt
	signature_private_key_file=C:\ProgramData\FreeLAN\laptop-nxo.key
	authority_certificate_file="..\config\ca.crt"
- CLI : KO
	c:\Program Files\FreeLAN\bin>freelan.exe -c ..\config\freelan.cfg
	Reading configuration file at: "c:\Program Files\FreeLAN\bin\..\config\freelan.cfg"
	Error: No such file: c:\Program Files\FreeLAN\bin\"..\config\ca.crt"
- Windows Service : KO

In fact it's not realy a problem because I used to put this kind of file in C:\ProgramData\... but it can be a problem since the example on the site include this "bug".

Regards.

**Comment by ereOn** [comment]
I could not reproduce the problem you mentionned: by quoting the path with `"` I could load certificates with spaces in their names.

I also updated the [configuration examples](http://freelan.org/configuration_examples.html#) page.
