### ISSUE TITLE
option dynamic_contact_folder instead dynamic_contact_file

### ISSUE THREAD

**Issue by richman1000000** [freelan-developers/freelan-all#44]
I am using freelan client from home and adding dynamic_contact_file line when it needed is really uncomfortable. The more certificates the more complicated this situation becomes. It would be easier to use one folder instead fol multiple files

**Comment by richman1000000** [comment]
using server mode is much better then my suggestion.
I thing we should close this issue

**Comment by ereOn** [comment]
@richman1000000 I still might implement this in the future, but indeed the server mechanism kind-of lowers the need for this feature.

Thanks for following up on your requests: I appreciate it.
