### ISSUE TITLE
Struggling to Build on Ubuntu 14.04

### ISSUE THREAD

**Issue by idistech** [freelan-developers/freelan-all#45]
Hi,  
Are there any further clarity on the build process for a linux install..
The 'teapot build' stage fails with no 'party' files.

Any guidance greatly appreciated.

Many Thanks

Gary

**Comment by ereOn** [comment]
Hi @idistech,

The build instructions can be blurry at times indeed.

There is no need for the `teapot` step on Linux. You can (and should) install the required dependencies from your package manager (`apt`) instead.

You'll need (from memory, please adapt if the name do not match exactly. I have no access to a linux environment at the time being) :
- `boost-all-devel`
- `libssl-dev`
- `libcrypto-dev` (not sure about this one - might be included in `libssl-dev`)
- `curl4-openssl-dev`

Once you have those, just type: `scons all samples` from the freelan root directory and you should be all set.

Let me know if that works.

**Comment by idistech** [comment]
Thanks so much for getting back.

Instructions look good. Im just doing it for a second time , just to confirm the process, and then Ill post the answer back !

Many Thanks again

Gary

**Comment by idistech** [comment]
This is what I did...

sudo apt-get install  libboost-all-dev libssl-dev git scons g++ libcurl4-openssl-dev
git clone https://github.com/freelan-developers/freelan-all.git
cd freelan-all
scons all samples

and its built...

many Thanks

Gary
