### ISSUE TITLE
Compiling from source

### ISSUE THREAD

**Issue by jackslayter** [freelan-developers/freelan-all#49]
Hi, I try to install freelan from sources on virtual debian machine before install on rpi.
my install is with  debian-7.4.0-amd64-netinst.iso.
I install all requirements
sudo apt-get install python-setuptools
sudo apt-get install gcc-4.7
sudo apt-get install build-essential
sudo apt-get install git-core zip
sudo wget http://prdownloads.sourceforge.net/scons/scons-2.3.3.zip
sudo python setup.py install
wget -c 'http://sourceforge.net/projects/boost/files/boost/1.55.0/boost_1_55_0.tar.bz2/download'
./bootstrap.sh
./b2 install
sudo apt-get install libboost-dev
git clone https://github.com/freelan-developers/freelan-all.git
scons
and I have errors
....
g++ -o build/release/apps/freelan/src/tools.o -c -Wno-missing-field-initializers --std=c++11 -Wall -Wextra -Werror -pedantic -Wshadow -O3 -isystem third-party/install/include -Ibuild/release/include build/release/apps/freelan/src/tools.cpp
In file included from build/release/include/cryptoplus/x509/../error/helpers.hpp:47:0,
                 from build/release/include/cryptoplus/x509/certificate_revocation_list.hpp:50,
                 from build/release/include/freelan/configuration.hpp:60,
                 from build/release/include/freelan/core.hpp:49,
                 from build/release/apps/freelan/src/tools.hpp:54,
                 from build/release/apps/freelan/src/tools.cpp:47:
build/release/include/cryptoplus/x509/../error/error.hpp:47:25: fatal error: openssl/err.h: No such file or directory
compilation terminated.
scons: *** [build/release/apps/freelan/src/tools.o] Error 1
scons: building terminated because of errors.

what is the problem ?
thank you

**Comment by tinoutinou** [comment]
Hi,

You should try to install ssl headers:
sudo apt-get install libssl-dev

**Comment by jackslayter** [comment]
thank you.
but now I have this error
scons: Reading SConscript files ...
scons: done reading SConscript files.
scons: Building targets ...
g++ -o build/release/libs/netlinkplus/src/manager.o -c -Wno-missing-field-initializers --std=c++11 -Wall -Wextra -Werror -pedantic -Wshadow -O3 -isystem third-party/install/include -Ibuild/release/libs/netlinkplus/include/netlinkplus -Ibuild/release/include build/release/libs/netlinkplus/src/manager.cpp
In file included from build/release/libs/netlinkplus/include/netlinkplus/messages.hpp:45:0,
                 from build/release/libs/netlinkplus/src/manager.cpp:46:
build/release/libs/netlinkplus/include/netlinkplus/generic_message.hpp: In member function 'nlmsghdr& netlinkplus::base_generic_message_type<Type, DataSize>::header()':
build/release/libs/netlinkplus/include/netlinkplus/generic_message.hpp:89:29: error: expected '<' before '<:' token
build/release/libs/netlinkplus/include/netlinkplus/generic_message.hpp:89:29: error: expected type-specifier before '<:' token
build/release/libs/netlinkplus/include/netlinkplus/generic_message.hpp:89:29: error: expected '>' before '<:' token
build/release/libs/netlinkplus/include/netlinkplus/generic_message.hpp:89:29: error: expected '(' before '<:' token
build/release/libs/netlinkplus/include/netlinkplus/generic_message.hpp:89:31: error: expected identifier before ':' token
build/release/libs/netlinkplus/include/netlinkplus/generic_message.hpp:89:57: error: expected ']' before ';' token
build/release/libs/netlinkplus/include/netlinkplus/generic_message.hpp: In lambda function:
build/release/libs/netlinkplus/include/netlinkplus/generic_message.hpp:89:57: error: expected '{' before ';' token
build/release/libs/netlinkplus/include/netlinkplus/generic_message.hpp: In member function 'nlmsghdr& netlinkplus::base_generic_message_type<Type, DataSize>::header()':
build/release/libs/netlinkplus/include/netlinkplus/generic_message.hpp:89:57: error: expected ')' before ';' token
In file included from build/release/libs/netlinkplus/src/manager.cpp:46:0:
build/release/libs/netlinkplus/include/netlinkplus/messages.hpp: At global scope:
build/release/libs/netlinkplus/include/netlinkplus/messages.hpp:122:35: error: '<::' cannot begin a template-argument list [-fpermissive]
build/release/libs/netlinkplus/include/netlinkplus/messages.hpp:122:35: note: '<:' is an alternate spelling for '['. Insert whitespace between '<' and '::'
build/release/libs/netlinkplus/include/netlinkplus/messages.hpp:122:35: note: (if you use '-fpermissive' G++ will accept your code)
build/release/libs/netlinkplus/include/netlinkplus/messages.hpp: In member function 'rtattr* netlinkplus::attribute_message<Type>::first_attribute()':
build/release/libs/netlinkplus/include/netlinkplus/messages.hpp:213:28: error: expected '<' before '<:' token
build/release/libs/netlinkplus/include/netlinkplus/messages.hpp:213:28: error: expected type-specifier before '<:' token
build/release/libs/netlinkplus/include/netlinkplus/messages.hpp:213:28: error: expected '>' before '<:' token
build/release/libs/netlinkplus/include/netlinkplus/messages.hpp:213:28: error: expected '(' before '<:' token
build/release/libs/netlinkplus/include/netlinkplus/messages.hpp:213:30: error: expected identifier before ':' token
build/release/libs/netlinkplus/include/netlinkplus/messages.hpp:213:76: error: expected ']' before ';' token
build/release/libs/netlinkplus/include/netlinkplus/messages.hpp: In lambda function:
build/release/libs/netlinkplus/include/netlinkplus/messages.hpp:213:76: error: expected '{' before ';' token
build/release/libs/netlinkplus/include/netlinkplus/messages.hpp: In member function 'rtattr* netlinkplus::attribute_message<Type>::first_attribute()':
build/release/libs/netlinkplus/include/netlinkplus/messages.hpp:213:76: error: expected ')' before ';' token
build/release/libs/netlinkplus/include/netlinkplus/messages.hpp: In member function 'rtattr* netlinkplus::attribute_message<Type>::next_attribute()':
build/release/libs/netlinkplus/include/netlinkplus/messages.hpp:223:28: error: expected '<' before '<:' token
build/release/libs/netlinkplus/include/netlinkplus/messages.hpp:223:28: error: expected type-specifier before '<:' token
build/release/libs/netlinkplus/include/netlinkplus/messages.hpp:223:28: error: expected '>' before '<:' token
build/release/libs/netlinkplus/include/netlinkplus/messages.hpp:223:28: error: expected '(' before '<:' token
build/release/libs/netlinkplus/include/netlinkplus/messages.hpp:223:30: error: expected identifier before ':' token
build/release/libs/netlinkplus/include/netlinkplus/messages.hpp:223:72: error: expected ']' before ';' token
build/release/libs/netlinkplus/include/netlinkplus/messages.hpp: In lambda function:
build/release/libs/netlinkplus/include/netlinkplus/messages.hpp:223:72: error: expected '{' before ';' token
build/release/libs/netlinkplus/include/netlinkplus/messages.hpp: In member function 'rtattr* netlinkplus::attribute_message<Type>::next_attribute()':
build/release/libs/netlinkplus/include/netlinkplus/messages.hpp:223:72: error: expected ')' before ';' token
build/release/libs/netlinkplus/include/netlinkplus/messages.hpp: At global scope:
build/release/libs/netlinkplus/include/netlinkplus/messages.hpp:254:56: error: '<::' cannot begin a template-argument list [-fpermissive]
build/release/libs/netlinkplus/include/netlinkplus/messages.hpp:254:56: note: '<:' is an alternate spelling for '['. Insert whitespace between '<' and '::'
In file included from build/release/libs/netlinkplus/src/manager.cpp:46:0:
build/release/libs/netlinkplus/include/netlinkplus/messages.hpp: In constructor 'netlinkplus::route_message_type<DataSize>::route_message_type(uint16_t, uint16_t)':
build/release/libs/netlinkplus/include/netlinkplus/messages.hpp:258:25: error: '<::' cannot begin a template-argument list [-fpermissive]
build/release/libs/netlinkplus/include/netlinkplus/messages.hpp:258:25: note: '<:' is an alternate spelling for '['. Insert whitespace between '<' and '::'
build/release/libs/netlinkplus/include/netlinkplus/messages.hpp: At global scope:
build/release/libs/netlinkplus/include/netlinkplus/messages.hpp:413:58: error: '<::' cannot begin a template-argument list [-fpermissive]
build/release/libs/netlinkplus/include/netlinkplus/messages.hpp:413:58: note: '<:' is an alternate spelling for '['. Insert whitespace between '<' and '::'
build/release/libs/netlinkplus/include/netlinkplus/messages.hpp: In constructor 'netlinkplus::address_message_type<DataSize>::address_message_type(uint16_t, uint16_t)':
build/release/libs/netlinkplus/include/netlinkplus/messages.hpp:417:25: error: '<::' cannot begin a template-argument list [-fpermissive]
build/release/libs/netlinkplus/include/netlinkplus/messages.hpp:417:25: note: '<:' is an alternate spelling for '['. Insert whitespace between '<' and '::'
build/release/libs/netlinkplus/include/netlinkplus/messages.hpp: At global scope:
build/release/libs/netlinkplus/include/netlinkplus/messages.hpp:491:56: error: '<::' cannot begin a template-argument list [-fpermissive]
build/release/libs/netlinkplus/include/netlinkplus/messages.hpp:491:56: note: '<:' is an alternate spelling for '['. Insert whitespace between '<' and '::'
build/release/libs/netlinkplus/include/netlinkplus/messages.hpp: In constructor 'netlinkplus::error_message_type::error_message_type(uint16_t, uint16_t)':
build/release/libs/netlinkplus/include/netlinkplus/messages.hpp:495:25: error: '<::' cannot begin a template-argument list [-fpermissive]
build/release/libs/netlinkplus/include/netlinkplus/messages.hpp:495:25: note: '<:' is an alternate spelling for '['. Insert whitespace between '<' and '::'
In file included from build/release/libs/netlinkplus/include/netlinkplus/messages.hpp:45:0,
                 from build/release/libs/netlinkplus/src/manager.cpp:46:
build/release/libs/netlinkplus/include/netlinkplus/generic_message.hpp: In member function 'nlmsghdr& netlinkplus::base_generic_message_type<Type, DataSize>::header() [with Type = netlinkplus::generic_message_type<ifaddrmsg, 1024ul>; long unsigned int DataSize = 1024ul]':
build/release/libs/netlinkplus/include/netlinkplus/generic_message.hpp:90:4: error: control reaches end of non-void function [-Werror=return-type]
In file included from build/release/libs/netlinkplus/src/manager.cpp:46:0:
build/release/libs/netlinkplus/include/netlinkplus/messages.hpp: In member function 'rtattr* netlinkplus::attribute_message<Type>::next_attribute() [with Type = netlinkplus::address_message_type<1024ul>]':
build/release/libs/netlinkplus/include/netlinkplus/messages.hpp:224:4: error: control reaches end of non-void function [-Werror=return-type]
In file included from build/release/libs/netlinkplus/include/netlinkplus/messages.hpp:45:0,
                 from build/release/libs/netlinkplus/src/manager.cpp:46:
build/release/libs/netlinkplus/include/netlinkplus/generic_message.hpp: In member function 'nlmsghdr& netlinkplus::base_generic_message_type<Type, DataSize>::header() [with Type = netlinkplus::generic_message_type<nlmsgerr, 1024ul>; long unsigned int DataSize = 1024ul]':
build/release/libs/netlinkplus/include/netlinkplus/generic_message.hpp:90:4: error: control reaches end of non-void function [-Werror=return-type]
build/release/libs/netlinkplus/include/netlinkplus/generic_message.hpp: In member function 'nlmsghdr& netlinkplus::base_generic_message_type<Type, DataSize>::header() [with Type = netlinkplus::generic_message_type<rtmsg, 1024ul>; long unsigned int DataSize = 1024ul]':
build/release/libs/netlinkplus/include/netlinkplus/generic_message.hpp:90:4: error: control reaches end of non-void function [-Werror=return-type]
In file included from build/release/libs/netlinkplus/src/manager.cpp:46:0:
build/release/libs/netlinkplus/include/netlinkplus/messages.hpp: In member function 'rtattr* netlinkplus::attribute_message<Type>::next_attribute() [with Type = netlinkplus::route_message_type<1024ul>]':
build/release/libs/netlinkplus/include/netlinkplus/messages.hpp:224:4: error: control reaches end of non-void function [-Werror=return-type]
build/release/libs/netlinkplus/include/netlinkplus/messages.hpp: In member function 'rtattr* netlinkplus::attribute_message<Type>::first_attribute() [with Type = netlinkplus::route_message_type<1024ul>]':
build/release/libs/netlinkplus/include/netlinkplus/messages.hpp:214:4: error: control reaches end of non-void function [-Werror=return-type]
cc1plus: all warnings being treated as errors
scons: *** [build/release/libs/netlinkplus/src/manager.o] Error 1
scons: building terminated because of errors.

google no help me

**Comment by ereOn** [comment]
Which version of `g++` are you using ?

    build/release/libs/netlinkplus/include/netlinkplus/messages.hpp:254:56: note: '<:' is an alternate spelling for '['. Insert whitespace between '<' and '::'

This means trigraph support is enabled and that is **not** a good thing. It may seem some of your tools are too old.

**Comment by jackslayter** [comment]
gcc-4.7

**Comment by ereOn** [comment]
After some research, here is [a question on StackOverflow](http://stackoverflow.com/questions/8338121/what-is-the-significance-of-the-syntax-in-c) that explains exactly what happens.

Basically you need to find a way to disable digraphs/trigraphs handling by your compiler (and possibly set the `CXXFLAGS` environment variable accordingly before building). FreeLAN's source is C++11 compliant so this is an issue with your tools.

I don't have a Debian Wheezy to test that on at the moment, so I'm afraid I can't do much more right now.

Feel free to reopen the ticket or submit a fix if you can find something that would fix on FreeLAN's level.

**Comment by jackslayter** [comment]
I have no knowledge to fix this

**Comment by ereOn** [comment]
@jackslayter Give it another go. I could reproduce the problem on a fresh debian install and altered the files so that the compilation goes through even with digraphs enabled.

**Comment by jackslayter** [comment]
Thank.
I reinstall all (new debian) and the error has disappeared but an other appear :/

scons: Reading SConscript files ...
scons: done reading SConscript files.
scons: Building targets ...
g++ -o build/release/libs/freelan/src/core.o -c -Wno-missing-field-initializers --std=c++11 -Wall -Wextra -Werror -pedantic -Wshadow -O3 -isystem third-party/install/include -Ibuild/release/libs/freelan/include/freelan -Ibuild/release/include build/release/libs/freelan/src/core.cpp
In file included from build/release/libs/freelan/src/core.cpp:46:0:
build/release/libs/freelan/include/freelan/core.hpp: In constructor 'freelan::core::core(boost::asio::io_service&, const freelan::configuration&)':
build/release/libs/freelan/include/freelan/core.hpp:584:18: error: 'freelan::core::m_tap_adapter_thread' will be initialized after [-Werror=reorder]
build/release/libs/freelan/include/freelan/core.hpp:583:28: error:   'boost::asio::io_service freelan::core::m_tap_adapter_io_service' [-Werror=reorder]
build/release/libs/freelan/src/core.cpp:375:2: error:   when initialized here [-Werror=reorder]
cc1plus: all warnings being treated as errors
scons: *** [build/release/libs/freelan/src/core.o] Error 1
scons: building terminated because of errors.

**Comment by ereOn** [comment]
@jackslayter Thanks for mentioning this. I forgot to commit a change I had locally.

Should work now :)

**Comment by jackslayter** [comment]
yes works , thank you.
for continued I follow https://github.com/freelan-developers/libasiotap/issues/5#issuecomment-35096778
but in freelan-all dir after scons install prefix=/usr/local/ , I don't found lib.....so for put in /usr/local/lib

**Comment by ereOn** [comment]
@jackslayter I'm sorry but I really don't understand your question.

Remember that the more effort you put in your questions, the easier it is for us to answer them.

**Comment by jackslayter** [comment]
what is the correct scons command to build freelan sources ?

**Comment by ereOn** [comment]
Well I'm a bit confused, it seems you have the right command from day 1:

`scons all` should build everything in both debug and release mode.
`scons samples` should build the samples (tests for the different components, but you probably don't need those)

Finally, you can install freelan to some other directory with:

    scons install --prefix=/some/location/of/your/choice

This will only copy the main binary though, so you might want to copy the configuration file (from `apps/freelan/config/freelan.cfg` to another place (likely `/etc/freelan.cfg`) manually.

**Comment by jackslayter** [comment]
Thank you so I done the correct syntax.
But I have problems, see https://github.com/freelan-developers/freelan-all/issues/53
Very thank you for your help
