### ISSUE TITLE
courtesy copies and Debian

### ISSUE THREAD

**Issue by leggewie** [freelan-developers/freelan-all#58]
Am I correct to assume that everything under libs and third-party represents a courtesy code copy of other projects that freelan is compiled against?  Debian doesn't like that.  It would be good to push that to a separate branch (or submodule as you did in the past, something I am not so familiar with in git).

**Comment by ereOn** [comment]
Regarding `libs`: in the past, freelan was split in several libraries that were supposed to evolve separately. That did never happen and I merged everything in one repository for maintenance reasons.

**You can consider everything in `libs` as direct source files for freelan, not something external.**

Regarding `third-pary`: on Linux this folder is not used at all. The only files that live in there are:
- A patched `libiconv` for Windows builds.
- A patch for Boost on OSX (which probably isn't needed anymore, I'll check if I can get rid of it this evening).

Does that answer address your concerns ?

**Comment by leggewie** [comment]
It seems I am mistaken for the most part.  libs/ is the libs you programmed for the freelan project.  Only thirdparty/ is code taken from outside sources.

third-party/source/libiconv-msvc (seems to be relevant only to Windows)
third-party/patches/boost/ (from a cursory look this one seems to be in Debian already in 1.55 and later)

**Comment by leggewie** [comment]
@ereOn Thank you for your comment.  I realized my mistake just this minute. Our comments now crossed.  If you can drop anything from thirdparty/ that would be good (for Debian and in general) but this is not a big concern anymore.  The fact that code isn't linked to is a legally valid argument, but the ftpmaster's don't want to check that and thus ALL shipped code has to pass some tests (legal and technical).  Again, I don't see much of a problem here anymore.

**Comment by ereOn** [comment]
I'm just reopening this as a reminder to delete the Boost patch if it is not needed anymore on OSX.
