### ISSUE TITLE
freelan2 identifies itself as OSX binary on a Linux host

### ISSUE THREAD

**Issue by leggewie** [freelan-developers/freelan-all#60]
On my Ubuntu machine:

$ ./install/bin/freelan2 --version
freelan 2.0.0 (1.1-osx-2825-gb799941) Mon 16 Mar 2015

**Comment by ereOn** [comment]
That's expected: it executes `git describe` to get the latest tag (which happens to be `1.1-osx` here).

It's a non issue because the next release will get its own tag which will not contain any platform specific naming.
