### ISSUE TITLE
integrate freelan in freetz

### ISSUE THREAD

**Issue by leggewie** [freelan-developers/freelan-all#61]
Reminder to self to do some work to compile freelan for freetz and publish the results.

[First steps - How to start your first freetz package](http://freetz.org/wiki/help/howtos/development/developer_information/package_development_start)

**Comment by ereOn** [comment]
Removing the milestone as it doesn't prevent the upcoming release.

**Comment by leggewie** [comment]
The people in the Freetz community are morons. I feel I can't be bothered with helping them. So sad to see so many projects crippled by technically skilled but socially inept people.

Closing ticket as wontfix.

**Comment by ereOn** [comment]
@leggewie That's too bad :(

Thanks for trying though, I appreciate it.

Do you have any online post/mail archive to reference here perhaps in case someone asks for this in the future ?
