### ISSUE TITLE
AUR PKGBUILD now available

### ISSUE THREAD

**Issue by g4jc** [freelan-developers/freelan-all#67]
Hello,
I took the time to make a PKGBUILD for this from git, you can find it here:
https://aur.archlinux.org/packages/freelan-git/

So if you'd like to mention it on the wiki:

For Arch Linux users, you may install the very latest build via -
yaourt -S freelan-git 

Also would appreciate someone leaving me a comment there if any package breaking things happen. (directory moving or changing to python3 for example).

Hope this helps someone, and thanks for the great program! :)

**Comment by ereOn** [comment]
@g4jc Awesome, thanks !

I'll close this up since it's not really an issue. I'll try to remember to post any breaking changes here but I can't promise I can do that for non-release builds.

**Comment by Justinzobel** [comment]
aur moved, please update.

**Comment by g4jc** [comment]
I don't have time to maintain the PKGBUILD in AUR at the moment, however here is the PKGBUILD. It still works: http://pastebin.com/raw/xpTYVpfN

**Comment by Justinzobel** [comment]
@ereOn are you able to maintain freelan in the AUR or one of the members of the team? That way it can be updated when you guys release.

**Comment by ereOn** [comment]
@Justinzobel I sadly can't commit to anything. Time is pretty scarce for me these days. I'm having a hard time finding time to fix upstream features so managing the different target platforms at the packaging level is even less likely.

**Comment by Split7fire** [comment]
I managed to package freelan-git. It is available now https://aur.archlinux.org/packages/freelan-git/

**Comment by ereOn** [comment]
@Split7fire That's great ! Thanks !
