### ISSUE TITLE
freelan stops without server

### ISSUE THREAD

**Issue by richman1000000** [freelan-developers/freelan-all#72]
When freelan client application is starting with 'servers mode enabled' and  server is unavailable, client do not retries to connect, just exits.

**Comment by ereOn** [comment]
@richman1000000 You are absolutely right that this is not a good behavior.

The client should indeed retry as long as it have to.

**Comment by richman1000000** [comment]
freelan 1.1 amd64

**Comment by ereOn** [comment]
@richman1000000 So yes, this has been fixed already.
